services:
  mediawiki:
    build:
      context: ./mediawiki
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9000:80
    environment:
      WIKI_PATH: '/wiki'
      BASE_URL: 'https://wiki.ece.iiasa.ac.at'
      MEDIAWIKI_DATABASE_HOST: 'mysql8.iiasa.ac.at'
      MEDIAWIKI_DATABASE_USER: 'ece'
      # SECRET VALUES ARE IN KUBERNETIS SECRETS 
      MEDIAWIKI_DATABASE_PASSWORD: '♪┏(・o･)┛♪'
      MEDIAWIKI_DATABASE_NAME: 'ece_wiki'
      MEDIAWIKI_DATABASE_PREFIX: 'wiki_'

      OPENID_TENANT_ID: '9b79b10b-0007-4e8a-b072-ad0c8cdc1aa5'
      OPENID_CLIENT_ID: '66f8d9b1-5b47-4060-b89f-4d964074bbd6'

      # SECRET VALUES ARE IN KUBERNETIS SECRETS 
      OPENID_CLIENT_SECRET: '〜⁠(⁠꒪⁠꒳⁠꒪⁠)⁠〜'

      # SECRET VALUES ARE IN KUBERNETIS SECRETS 
      MEDIAWIKI_SECRET_KEY: 'ᕙ( •̀ ᗜ •́ )ᕗ'

    volumes:
      - mediawiki_images:/var/www/html/wiki/images
    networks:
      - wiki-network

networks:
  wiki-network:
    external: true

volumes:
  mediawiki_images:
