
version: '3'
services:
  mediawiki:
    privileged: true
    image: ene-docker.iiasa.ac.at/mediawiki:1.35.2
    restart: always
    ports:
      - 9000:80
    links:
      - database
    environment:
      DEBUG: 'true'
      WIKI_PATH: '/wiki'
      BASE_URL: 'http://localhost:9000'
      MEDIAWIKI_DATABASE_HOST: 'database'
      MEDIAWIKI_DATABASE_USER: wikiuser
      MEDIAWIKI_DATABASE_PASSWORD: example
      MEDIAWIKI_DATABASE_NAME: mywiki
      MEDIAWIKI_DATABASE_PREFIX: ‘wiki_’

      OPENID_TENANT_ID: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
      OPENID_CLIENT_ID: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
      OPENID_CLIENT_SECRET: 'XXXXXXXXXXXXXXXXXXXXX'

      # WARNING: Test SK
      MEDIAWIKI_SECRET_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
      MEDIAWIKI_UPGRADE_KEY: 'XXXXXXX'
    volumes:
      - /var/www/html/wiki/images
  database:
    image: mariadb
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: mywiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./dbdata:/var/lib/mysql
